--Task 20 — Product count in each category
SELECT 
    c.category_name,
    COUNT(p.product_id) AS product_count
FROM production.categories AS c
LEFT JOIN production.products AS p
    ON c.category_id = p.category_id
GROUP BY c.category_name;
--Task 21 — Average list price per brand
SELECT 
    b.brand_name,
    AVG(p.list_price) AS average_price
FROM production.brands AS b
JOIN production.products AS p
    ON b.brand_id = p.brand_id
GROUP BY b.brand_name;
--Task 22 — Total orders for each store
SELECT 
    s.store_name,
    COUNT(o.order_id) AS total_orders
FROM sales.stores AS s
LEFT JOIN sales.orders AS o
    ON s.store_id = o.store_id
GROUP BY s.store_name;
--Task 23 — Total revenue per order

--Revenue = quantity × list_price × (1 - discount)

SELECT 
    oi.order_id,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.order_items AS oi
GROUP BY oi.order_id;
--Task 24 — Each customer's total number of orders

--Sort by order count descending.

SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS order_count
FROM sales.customers AS c
LEFT JOIN sales.orders AS o
    ON c.customer_id = o.customer_id
GROUP BY 
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY order_count DESC;
--Task 25 — Brand with the highest average product price
SELECT TOP 1
    b.brand_name,
    AVG(p.list_price) AS average_price
FROM production.brands AS b
JOIN production.products AS p
    ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY average_price DESC;
--Task 26 — Categories with more than 50 products
SELECT 
    c.category_name,
    COUNT(p.product_id) AS product_count
FROM production.categories AS c
JOIN production.products AS p
    ON c.category_id = p.category_id
GROUP BY c.category_name
HAVING COUNT(p.product_id) > 50; 

--Task 27 — Total revenue generated by each store
SELECT 
    s.store_id,
    s.store_name,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.stores AS s
JOIN sales.orders AS o
    ON s.store_id = o.store_id
JOIN sales.order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY 
    s.store_id,
    s.store_name;
--Task 28 — Staff members who handled more than 50 orders
SELECT 
    st.staff_id,
    st.first_name,
    st.last_name,
    COUNT(o.order_id) AS total_orders
FROM sales.staffs AS st
JOIN sales.orders AS o
    ON st.staff_id = o.staff_id
GROUP BY 
    st.staff_id,
    st.first_name,
    st.last_name
HAVING COUNT(o.order_id) > 50
ORDER BY total_orders DESC;